### ISSUE TITLE
CohortMethod KaplanMeier plot cosmetics to improve

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/OhdsiShinyModules#11] opened 2022-08-31 12:58 UTC
The current Kaplan Meier plot could be improve in 2 primary ways:

1.  List the cohort name, instead of the cohortID in the legend (currently, the cohortID is not exposed anywhere else in the app that I can see, so one doesn't know what the two lines represent).  Alternative could be making clear that Red is Target and Blue is 'Comparator', since at least that information is exposed in the left dropdowns.
2.  Scaling of the x-axis (and coresponding time-at-risk) should be determined based on available data, to avoid labeling overlap.   Below is example plot that shows issue:

![image](https://user-images.githubusercontent.com/731930/187683730-90d006e3-3f5d-4e0b-b8e9-9cd7bbac56ff.png)

**Comment by pbr6cornell** [comment] 2022-09-21 01:23
Still looks like issue in @jreps release:

![image](https://user-images.githubusercontent.com/731930/191393430-ea744d95-490d-4f1c-824b-4653f1d9874d.png)

**Comment by jreps** [comment] 2022-12-08 18:47
This was also caused by NA values in the results being replaced by 0 values in the databases - it is now fixed in develop

**Closed** 2023-02-14 17:38 UTC
Labels: enhancement, fixed in develop
