### ISSUE TITLE
Characterization -> Cohort Summary -> Cohort Comparison --> Binary:  Censoring 0 & Download (Filtered)

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/OhdsiShinyModules#308] opened 2024-07-19 17:02 UTC
**ISSUE 1**
Values should be censored between 1 and 5, when the value is 0 it does not need to be censored.  

Her is an example of the report for a drug that shows rows for a drug that doesn't start until 2019.  The values 2015-2018 should say 0 not < min threshold.
![image](https://github.com/user-attachments/assets/92a14492-097e-4762-a719-4a2b75a861d5)

Here is the ARES report for that same exposure:
![image](https://github.com/user-attachments/assets/cf94daf6-68d3-4c7c-906b-bab88751c81e)

**ISSUE 2**
The Download (Filtered) button doesn't not download any file. 

Generated with OhdsiShinyModules v2.1.5.9000 and ShinyAppBuilder v2.0.1.9000

**Comment by jreps** [comment] 2024-08-22 19:24
This will be hard to do as the < min threshold means the covariate was too rare for FE to extract, but doesn't mean it is 0.

**Comment by nhall6** [comment] 2024-09-23 12:54
Closing for now as it is by design.

**Closed by nhall6** 2024-09-23 12:54 UTC
Labels: byDesign
