### ISSUE TITLE
CohortMethod Systematic Error plot

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/OhdsiShinyModules#12] opened 2022-08-31 13:35 UTC
I suspect that the Systematic Error plot is counting negative controls which did not yield estimates in the denominator, which is making the count of estimates look too high and the % of CIs including 1 too low:

![image](https://user-images.githubusercontent.com/731930/187691215-ed1aaa65-7fc1-4122-a98f-f92b16dbd53f.png)

If you look at these plots, there are not 106 dots, and the % with CI in 1 shoudl be very close to 95%.

**Comment by pbr6cornell** [comment] 2022-09-21 01:22
@jdide , i think there's still an issue here.   Look at this plot, theres a dark dot at 0,0, which I think is invalid data, but I believe it's getting counted in the proportion:

![image](https://user-images.githubusercontent.com/731930/191393279-c8f601a9-c3fe-4b7e-9f9e-639b181f8067.png)

**Comment by jreps** [comment] 2022-12-08 18:47
This was caused by NA values being replaced by 0, it is now fixed in develop

**Closed as completed** 2023-02-14 17:37 UTC
Labels: bug, fixed in develop
