### ISSUE TITLE
Characterization --> Exposed Cases Summary --> Risk Factor --> Continuous Feature Table | Incorrect Columns Displayed

### ISSUE THREAD

**Issue by conovermitch** [OHDSI/OhdsiShinyModules#306] opened 2024-07-16 16:17 UTC
**Strategus dashboard package versions:** Generated with OhdsiShinyModules v2.1.5.9000 and ShinyAppBuilder v2.0.1.9000

**Location of issue within Strategus dashboard:** Characterization --> Exposed Cases Summary --> Risk Factor --> Continuous Feature Table

**Expected (optimal) behavior:** The continuous features table should compare the distribution of continuous covariates among patients in the target who go on to become cases during the specified time-at-risk (TAR) to patients who _do not_ go on to become cases.  This (correct) behavior is what is shown in the Binary Feature Table.

**Actual behavior:** The Continuous Features Table appears to show a comparison of patients in the target who go on to become cases during the specified TAR to patients in the target.  There are no columns that contain data for patients in the target who _do not_ go on to become cases. Initially, I thought it was possible that the data was correct but the column labels were wrong; however, the "# of Target with Feature" column appears to reflect the count of people included in the target cohort in general indicating that the incorrect columns have been selected for display in the application.  Note that I checked the "Select Columns to Display" drop-down to see if the correct risk-factor data could be selected but it is not available.

I have provided a screen grab below to clarify what I am seeing. Please do not hesitate to reach out if I can provide any further information to clarify the issue.

![image](https://github.com/user-attachments/assets/84823fa2-282e-4a23-868d-21ce79bc6b6e)

**Comment by jreps** [comment] 2024-08-22 19:21
This is by design due to efficiency in what data we extract. The non-cases = (target - excluded - cases) but we can't calculate the quantiles for the target minus the excludes minus the cases with the quantiles from target, quantiles from excludes and quantiles from the cases.  The target values should be close to the non-cases though.

**Comment by nhall6** [comment] 2024-09-23 12:55
Closing for now as a "good to know"

**Closed by nhall6** 2024-09-23 12:55 UTC
Labels: byDesign, GoodToKnown
